FROM ubuntu:24.04
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      bash ca-certificates g++ docker.io docker-compose-v2 && \
    rm -rf /var/lib/apt/lists/*
