FROM python:3.11-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      bash curl jq postgresql-client ca-certificates procps g++ libssl-dev && \
    rm -rf /var/lib/apt/lists/*
